const axios = require("axios");
require("dotenv").config();

/**
 * Sends a formatted Surplus Audit to a Discord Webhook.
 */
async function postToDiscord(reportData) {
    const embed = {
        title: "🛡️ Treasury Rebalance: Surplus Audit",
        color: 0x00ff00, // Green for success
        fields: [
            { name: "Order ID", value: `\`${reportData.orderId.slice(0, 10)}...\`` },
            { name: "Execution Efficiency", value: `${reportData.efficiency}%`, inline: true },
            { name: "MEV Surplus Captured", value: `+${reportData.surplus} ${reportData.token}`, inline: true },
            { name: "Venue", value: "CoW Protocol (MEV Protected)", inline: false }
        ],
        footer: { text: "Generated by Treasury-Surplus-Auditor v1.0" },
        timestamp: new Date()
    };

    try {
        await axios.post(process.env.DISCORD_WEBHOOK_URL, { embeds: [embed] });
        console.log("Report broadcasted to Discord.");
    } catch (err) {
        console.error("Failed to send Discord notification:", err.message);
    }
}

// Example Trigger
postToDiscord({
    orderId: "0x1234567890abcdef1234567890abcdef",
    efficiency: "100.4",
    surplus: "12.5",
    token: "USDC"
});
